name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:
    inputs:
      run_build:
        description: "Run Build and Push job?"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"
      run_deploy:
        description: "Run Deploy job?"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || github.event.inputs.run_build == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create docker-compose .env
        run: |
          cat << EOF > .env
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          EOF

      - name: Build and Push Docker Images
        run: |
          docker compose build
          docker compose push

  deploy:
    name: Deploy to AWS EC2  
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || github.event.inputs.run_deploy == 'true'
    steps:
      - name: Create SSH Key File
        run: |
          echo "${{ secrets.EC2_KEY }}" > shuttlezone.pem
          chmod 600 shuttlezone.pem 

      - name: SSH into AWS EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i shuttlezone.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker stop shuttlezone-frontend-container || true
          docker rm shuttlezone-frontend-container || true
          docker stop shuttlezone-backend-container || true
          docker rm shuttlezone-backend-container || true

          docker pull ${{ secrets.DOCKER_USERNAME }}/ckrooms-frontend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/ckrooms-backend:latest

          cat << EOFF > frontend.env
          REACT_APP_API_BASE_URL=http://${{ secrets.EC2_HOST }}:8000
          EOFF

          cat << EOFF > backend.env
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          EOFF

          docker run -d --name shuttlezone-frontend-container \
            -p 3000:3000 \
            --env-file frontend.env \
            --restart always \
            ${{ secrets.DOCKER_USERNAME }}/ckrooms-frontend:latest

          docker run -d --name shuttlezone-backend-container \
            -p 8000:8000 \
            --env-file backend.env \
            --restart always \
            ${{ secrets.DOCKER_USERNAME }}/ckrooms-backend:latest
          EOF
